name: Docker image CI

on:
  push:
    paths:
      - docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build app
      uses: docker/compose@v1
      with:
        file: docker-compose.yml
        command: build
